In [1]:
import numpy as np

Arr1 = np.array([10,20,30,40])
Arr2 = np.array([50,60,70,80])
New_Arr = np.add(Arr1,Arr2)

display(New_Arr)

array([ 60,  80, 100, 120])

In [2]:
import numpy as np

Arr1 = np.array([10,20,30,40])
Arr2 = np.array([12,15,22,33])
New_Arr = np.subtract(Arr1,Arr2)

display(New_Arr)

array([-2,  5,  8,  7])

In [3]:
import numpy as np

Arr1 = np.array([11,21,31,41])
Arr2 = np.array([55,66,77,88])
New_Arr = np.multiply(Arr1,Arr2)

display(New_Arr)

array([ 605, 1386, 2387, 3608])

In [4]:
import numpy as np

Arr1 = np.array([10,20,30,40])
Arr2 = np.array([2,3,5,7])
New_Arr = np.divide(Arr1,Arr2)

display(New_Arr)

array([5.        , 6.66666667, 6.        , 5.71428571])

In [5]:
import numpy as np

Arr1 = np.array([5,10,15,20])
Arr2 = np.array([3,4,5,6])
New_Arr = np.power(Arr1,Arr2)

display(New_Arr)

array([     125,    10000,   759375, 64000000], dtype=int32)

In [6]:
import numpy as np

Arr1 = np.array([20,40,60,80])
Arr2 = np.array([3,5,7,9])
New_Arr = np.divmod(Arr1,Arr2)

display(New_Arr)

(array([6, 8, 8, 8], dtype=int32), array([2, 0, 4, 8], dtype=int32))

In [7]:
import numpy as np

Arr = np.trunc([4.226, -5.667, 7.436, -3.668])

display(Arr)

array([ 4., -5.,  7., -3.])

In [8]:
import numpy as np

Arr1 = np.array([1,2,3,4])
Arr2 = np.array([10,20,30,40])
Arr3 = np.array([100,200,300,400])
New_Arr = np.sum([Arr1, Arr2, Arr3])

display(New_Arr)

1110

In [9]:
import numpy as np

Arr = np.array([11,21,31,41,51])
New_Arr = np.cumsum(Arr)

display(New_Arr)

array([ 11,  32,  63, 104, 155], dtype=int32)

In [4]:
import numpy as np

Arr1 = np.array([1,2,3,4])
Arr2 = np.array([10,20,30,40])
New_Arr = np.prod([Arr1, Arr2])

display(New_Arr)

5760000